# Generated by Django 5.2.5 on 2025-09-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='', max_length=255),
        ),
    ]
