# Generated by Django 5.2.5 on 2025-09-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_password_user_password_hash_user_salt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
    ]
