# Generated by Django 5.2.6 on 2025-09-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
