# Generated by Django 5.2.6 on 2025-09-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
