# Generated by Django 5.2.6 on 2025-09-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempts',
            field=models.IntegerField(default=0, help_text='0 means unlimited attempts, any positive number restricts attempts'),
        ),
    ]
