# Generated by Django 5.2.6 on 2025-09-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quizattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
