# Generated by Django 5.2.5 on 2025-09-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quizattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
