# Generated by Django 5.2.6 on 2025-09-09 12:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0005_alter_course_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Center latitude in decimal degrees', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Center longitude in decimal degrees', max_digits=9)),
                ('radius_meters', models.PositiveIntegerField(default=100, help_text='Allowed radius in meters')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Session start time (UTC-aware)')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration of session in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Quick flag; session may be auto-deactivated when expired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_sessions', to='courses.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_sessions', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='GeofenceAccessLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_meters', models.FloatField(blank=True, null=True)),
                ('allowed', models.BooleanField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_logs', to='accounts.user')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='courses.geofencesession')),
            ],
        ),
    ]
