# Generated by Django 5.2.6 on 2025-09-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_geofencesession_geofenceaccesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofenceaccesslog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='geofenceaccesslog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='geofencesession',
            name='latitude',
            field=models.DecimalField(decimal_places=16, help_text='Center latitude in decimal degrees', max_digits=24),
        ),
        migrations.AlterField(
            model_name='geofencesession',
            name='longitude',
            field=models.DecimalField(decimal_places=16, help_text='Center longitude in decimal degrees', max_digits=24),
        ),
    ]
