# Generated by Django 5.2.5 on 2025-09-17 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_alter_geofenceaccesslog_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('welcome_message', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_weeks', to='courses.course')),
            ],
            options={
                'ordering': ['course', 'week_number'],
                'unique_together': {('course', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='PreparationResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_resources', to='preparation.preparationweek')),
            ],
            options={
                'ordering': ['week', 'title'],
            },
        ),
    ]
