# Generated by Django 5.2.6 on 2025-09-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='points',
            new_name='total_points',
        ),
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pointrequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='pointrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointrequest',
            name='request_type',
            field=models.CharField(choices=[('question', 'Question'), ('answer', 'Answer')], default='question', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='course',
        ),
    ]
