# Generated by Django 5.2.6 on 2025-09-13 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0007_alter_geofenceaccesslog_latitude_and_more'),
        ('points', '0002_rename_points_leaderboard_total_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='request_type',
            field=models.CharField(choices=[('question', 'Question (+10)'), ('answer', 'Answer (+20)')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together={('student', 'course')},
        ),
    ]
