# Generated by Django 5.2.6 on 2025-09-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('points', '0003_leaderboard_course_alter_leaderboard_student_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='points',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='request_type',
            field=models.CharField(choices=[('question', 'Question'), ('answer', 'Answer')], default='question', max_length=20),
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='course',
        ),
    ]
