# Generated by Django 5.2.6 on 2025-09-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_alter_leaderboard_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrequest',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='request_type',
            field=models.CharField(choices=[('question', 'Question'), ('answer', 'Answer')], max_length=20),
        ),
    ]
