# Generated by Django 5.2.6 on 2025-09-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_pointrequest_is_notified_alter_pointrequest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrequest',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointrequest',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointrequest',
            name='notification_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='request_type',
            field=models.CharField(choices=[('question', 'Question (+10)'), ('answer', 'Answer (+20)')], max_length=20),
        ),
    ]
