# Generated by Django 5.2.6 on 2025-09-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_pointrequest_declined_pointrequest_declined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrequest',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pointrequest',
            name='session_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
