# Generated by Django 5.2.6 on 2025-09-22 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_geofenceaccesslog_latitude_and_more'),
        ('points', '0007_pointrequest_description_pointrequest_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
