# Generated by Django 5.2.6 on 2025-09-22 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0007_alter_geofenceaccesslog_latitude_and_more'),
        ('points', '0008_leaderboard_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='accounts.user'),
        ),
    ]
